### ISSUE TITLE
Erro ao executar o Migration por primeira vez

### ISSUE THREAD

**Issue by upcesar** [SharebookBR/sharebook-backend#103]
Tinha configurado um banco válido. 

Até testei usando o "Update-Database" e ele só está criando a tabela "Book" e não "User"

Vide imagens abaixo:
![image](https://user-images.githubusercontent.com/5758510/45008449-1d59f980-afd9-11e8-88f8-0753a95286e5.png)

![image](https://user-images.githubusercontent.com/5758510/45008506-7b86dc80-afd9-11e8-8064-4db273edcd75.png)

**Comment by Cussa** [comment]
Selecione o projeto ShareBook.Repository na combo Default Project e tente novamente.

**Comment by upcesar** [comment]
Foi executada novamente a Migration selecionando como DefaultProject ShareBook.Data", quanto "ShareBook.Repository", sem resultado nenhum.

![image](https://user-images.githubusercontent.com/5758510/45036875-00064900-b034-11e8-8b68-a22a94fe7e78.png)

![image](https://user-images.githubusercontent.com/5758510/45036955-380d8c00-b034-11e8-9bd4-19544d19c939.png)

**Comment by Cussa** [comment]
@upcesar copie o log completo do erro e também a configuração do web.config que você está usando.

**Comment by upcesar** [comment]
Deletei meu repositório e refez o Fork. A sincronização estava incompleta.
