### ISSUE TITLE
21 - EU, ENQUANTO RODRIGO DOADOR PRECISO SER NOTIFICADO SOBRE NOVOS INTERESSADOS DE FORMA A MANTER MEU ENGAJAMENTO.

### ISSUE THREAD

**Issue by Cussa** [SharebookBR/sharebook-backend#142]
CRITÉRIOS DE ACEITE.
- NÃO INFORMAR DADOS PESSOAIS DO INTERESSADO.
- MOSTRAR APENAS APELIDO E JUSTIFICATIVA.
- EXEMPLO DE APELIDO: INTERESSADO 3.
- DEIXAR CLARO QUE EH APENAS UMA NOTIFICAÇÃO E QUE ELE PRECISA ESPERAR A 'DATA DE DECISÃO.'

Em alinhamento feito com o @raffacabofrio  definimos que o apelido que irá no e-mail de aviso ao doador, será gerado no momento da solicitação do livro, será composto da palavra "Interessado" + o total de interessados no livro naquele momento. exemplo.

Se momento da solicitação existirem 2 pessoas interessadas em um livro, o próximo apelido será a "interessado 03".

Essa informação não será persistida.

**Comment by raffacabofrio** [comment]
Não estou recebendo esse email em DEV.

**Comment by marcios** [comment]
O problema de não enviar e-mail está no livro que no campo chooseDate está nulo. quando chega no momento de enviar o e-mail ao doador, usa-se este campo para informar ao doador sobre a data de decisão. 
eu havia feito uma tratativa para isso, verificando se o campo estava nulo, se sim, aplicava a regra para obter a data de decisão (data de cadastro + 5 dias). mas o @Cussa  aconselhou a remover este trecho pq quando chegasse este momento o livro ja deveria ter a choose date preenchida. então deve-se analisar o momento de aprovação do livro e entender pq não esta gerando a choosedate
