### ISSUE TITLE
Bug no endpoint de recuperar senha.

### ISSUE THREAD

**Issue by raffacabofrio** [SharebookBR/sharebook-backend#167]
ForgetEmail está recebendo o e-mail como parâmetro na query String... e se o e-mail tiver alguns caracteres diferentes (mas válidos, como + ), a api não funciona.

**Comment by viniciustr** [comment]
Após investigação da mensagem de erro, encontrei o seguinte link: https://stackoverflow.com/questions/7739233/double-escape-sequence-inside-a-url-the-request-filtering-module-is-configured

Algumas respostas sugerem uma modificação no Web.config para tirar a validação de caracteres reservados que o IIS está fazendo, mas acho melhor não fazer dessa maneira.

Como o endpoint da API já é um POST, recomendo movermos o endereço de email para o corpo da requisição. Assim, o problema é contornado de maneira melhor. Ficaria algo bem simples:

```json
{
  "email": "fulano+teste@gmail.com"
}
```

O único porém é que o front precisará ser modificado também. No entanto, mudança é pequena. Vamos fazer assim?

**Comment by wantero** [comment]
Por mim fechou. A parte do front pode deixar que implemento assim que o Backend estiver em dev.

**Comment by raffacabofrio** [comment]
Top. Eu também concordo. Bora nesse caminho então.

**Comment by viniciustr** [comment]
@wantero como o backend já está pronto, podemos mandar bala no front!
