### ISSUE TITLE
Erro ao mudar a capa de um livro.

### ISSUE THREAD

**Issue by raffacabofrio** [SharebookBR/sharebook-backend#209]
Para reproduzir esse erro:
- Entre no ambiente de DEV. http://dev.sharebook.com.br/
- Faça o login como ADM. vagner@sharebook.com, senha 12345
- Vá para tela de editar livro.
- Abra o console dev. ( F12 no windows )
- Mude a foto e tente salvar.

Repare que no console vc vai ter o erro.
status: 500

ArgumentNullException: Value cannot be null.
 Parameter name: path2

ShareBook.Api.Middleware.ExceptionHandlerMiddleware+<Invoke>d__2.MoveNext() in ExceptionHandlerMiddleware.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by marcios** [comment]
Estarei atuando neste fix

**Comment by raffacabofrio** [comment]
Tudo certo amigão. Fechando aqui.

Obrigado @marcios 👊

**Comment by raffacabofrio** [comment]
Em alguns cenários mais raros esse erro ainda ocorre. No geral consigo mudar a capa do livro de boas.

Suspeito que tenha a ver com o tipo do arquivo. JPG vs JPEG vs NPG... Temos que investigar...

Se não me engano o front sempre redimensiona a imagem e envia como JPG. Certo @wantero ?

**Comment by marcios** [comment]
blz, voltamos pra fase de analise!!

**Comment by wantero** [comment]
O form permite os seguintes tipos de imagem: [allowedExtensions]="['jpg','jpeg','png']"

**Comment by raffacabofrio** [comment]
Não tivemos nenhum caso desse há muito tempo. Fechando aqui.
