### ISSUE TITLE
Senhas perdidas

### ISSUE THREAD

**Issue by raffacabofrio** [SharebookBR/sharebook-backend#219]
Já aconteceu comigo, com @wantero e com @davimattos.

Em algum momento nossa senha fica inválida. Mas temos certeza que não mudamos.

Precisamos investigar. Suspeito que seja algum outro processo esteja zerando as senhas. Eu sugiro olhar com cuidado os processos de mudar senha e o de recuperar senha.

**Comment by wantero** [comment]
@raffacabofrio consegui identificar que a senha está sendo zerada após o facilitador escolher um vencedor de um livro para o doador.

**Comment by marcios** [comment]
@wantero, qual o endpoint?

**Comment by wantero** [comment]
@marcios /api/Book/Donate/{bookId}. Pelo que o @raffacabofrio identificou, pode ser um problema com o cleanup().

**Comment by marcios** [comment]
blz @wantero  vou analisar este bug mais tarde. deixa comigo.
