### ISSUE TITLE
SSL não é completamente seguro

### ISSUE THREAD

**Issue by mljunior** [SharebookBR/sharebook-backend#265]
Algumas imagens precisam de revisão, pois não contém https no link, deixando assim o certificado SSL "quebrado".

![ssl](https://user-images.githubusercontent.com/42322809/56895713-421b4980-6a60-11e9-9950-231d8100b63d.jpeg)
![quebrado](https://user-images.githubusercontent.com/42322809/56895714-421b4980-6a60-11e9-949e-7b225e51bd26.jpeg)

**Comment by saraiva1989** [comment]
Acessei essa pagina e não possui mais o problema de SSL.

**Comment by raffacabofrio** [comment]
@saraiva1989 obrigado por avisar. Vou fechar essa issue então. Tmj 👊

**Comment by wantero** [comment]
@raffacabofrio aquela alteração que você fez na config para resolver o problema das imagens do final de semana, resolveu isso.
