### ISSUE TITLE
[BUG] Usuários não estão recebendo e-mail com código de rastreio

### ISSUE THREAD

**Issue by wantero** [SharebookBR/sharebook-backend#266]
Ao informar o código de rastreio pelo Sharebook, o vencedor não está recebendo e-mail com a informação do código de rastreio.

![image](https://user-images.githubusercontent.com/12854717/57477667-951aab00-726f-11e9-9a10-cb08c835d530.png)

**Comment by raffacabofrio** [comment]
Fiz um duplo teste na minha máquina e no ambiente de dev e em ambos os casos o email foi enviado corretamente. Fechando a issue aqui.

Talvez seja interessante orientar os usuários a adicionarem o email do sharebook em suas white list, pra evitar ir pra caixa de spam. Eu fiz isso no meu gmail.
