### ISSUE TITLE
Site retornando dados de usuário

### ISSUE THREAD

**Issue by danilobbezerra** [SharebookBR/sharebook-backend#333]
Olá pessoal.
Trabalhei com o Rafa alguns anos atras na SuperDigital e sempre acompanho via linkedin algumas postagem do shareebok, mas nunca pude contribuir.
Bom se eu puder contribuir de alguma forma estou a disposição.

Navegando pelo site deslogado percebi que a busca está muito boa rápida, então fui ver como era o mecanismo e percebi que ele chama uma URL: https://www.sharebook.com.br/api/book/Slug/xxxxxxxx

Porem esse cara está retornando informações sigilosas ao meu ver, como Nome, e-mail perfil do linkedin etc...
Seria isso correto mesmo?
Detalhe não analisei o código do backend.

Valeu abs.

**Comment by raffacabofrio** [comment]
Salve Danilo. Blz? Quanto tempo heim.

Vc tem razão. Precisamos mudar esse endpoint. O front nem precisa desses dados.

Vamos manter essa issue aberta, e aguardar uma contribuição. Um pulo request.

Obs: estamos fazendo upgrade pro .Net core 3.1. A branch mais indicada pra trabalhar eh a develop.

Obrigado pela força. Tmj.

**Comment by danilobbezerra** [comment]
Blz vou contribuir vou baixar a branch de dev.

**Comment by raffacabofrio** [comment]
Na minha última PR resolvi esse problema nesse endpoint do slug. Está nos ambientes de DEV e STG e será publicado na próxima entrega.

Entretanto olhei nosso swagger e reparei que temos esse problema em outros endpoints também. Vou listar aqui.

- GET /api/Book/Top15NewBooks
- GET /api/Book/Random15Books
- GET /api/Book/Title/{title}/{page}/{items}
- GET /api/Book/Author/{author}/{page}/{items}
- GET /api/Book/Category/{categoryId}/{page}/{items}

**Comment by raffacabofrio** [comment]
https://github.com/SharebookBR/sharebook-backend/pull/355
