### ISSUE TITLE
[URGENTE] NÃO CONSIGO DOAR LIVRO USANDO IPHONE

### ISSUE THREAD

**Issue by raffacabofrio** [SharebookBR/sharebook-backend#95]
Ambientes testados: DEV, STG e PRD.

Perfil Usuário: comum. ( Não pode entrar como adm )

Reproduzir o erro é fácil. Tente doar um livro no ambiente de DEV.

dev.sharebook.com.br

**Comment by raffacabofrio** [comment]
Em tempo. Esse mesmo erro também ocorre no Mac.

Reportado pelo Camilo agora a pouco: Macbook, Chrome 64.03282.186

**Comment by tomatealbertini** [comment]
Testei num iMac High Sierra com Chrome Versão 68.0.3440.106 e funcionou a doação de livro.

**Comment by raffacabofrio** [comment]
Fechando aqui pra abrir no lugar certo.
